// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmKVVc05J6c5a9sMlkcBg9Skwhvlizlek',
    appId: '1:398828447616:android:9800a568224860d4290365',
    messagingSenderId: '398828447616',
    projectId: 'zef-a002',
    storageBucket: 'zef-a002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoM3v4Lbr8hmckqBzCpTLDUKH8fxxN764',
    appId: '1:398828447616:ios:2cec35145cf40a52290365',
    messagingSenderId: '398828447616',
    projectId: 'zef-a002',
    storageBucket: 'zef-a002.appspot.com',
    iosClientId: '398828447616-qjegp9lhernv2oebts5fipfnc8j4nsr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.economyCondition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoM3v4Lbr8hmckqBzCpTLDUKH8fxxN764',
    appId: '1:398828447616:ios:e2a9a5be72321fa4290365',
    messagingSenderId: '398828447616',
    projectId: 'zef-a002',
    storageBucket: 'zef-a002.appspot.com',
    iosClientId: '398828447616-0ircvjf1q3fkbvmm5umue3c40nag52od.apps.googleusercontent.com',
    iosBundleId: 'com.example.economyCondition.RunnerTests',
  );
}
